### ISSUE TITLE
Slack Chat ops 500 server error

### ISSUE THREAD

**Issue by dark-brains** [grafana/oncall#3834]
### What went wrong?

**What happened**: When trying to connect slack chat ops oncall/grafana returned 500 Internal server error
-

**What did you expect to happen**:When trying to connect slack chat ops oncall/grafana returned 500 Internal server error.
-

### How do we reproduce it?

1. Open Grafana OnCall and do X
2. Now click button Y
3. Wait for the browser to crash. Error message says: "Error..."

### Grafana OnCall Version

helm 1.3.100

### Product Area

Chatops

### Grafana OnCall Platform?

Kubernetes

### Anything else to add?

When trying to connect slack chat ops oncall/grafana returned 500 Internal server error.
![Screenshot from 2024-02-03 01-14-10](https://github.com/grafana/oncall/assets/114874694/91cdb0c1-4f8b-46c6-81a2-9dd87edff110)
![Screenshot from 2024-02-03 01-14-24](https://github.com/grafana/oncall/assets/114874694/0ccc26bc-dd71-478d-9e99-7e4f418dfeae)

**Comment by dark-brains** [comment]
```    response = self._call_api(method=requests.get, url=url, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/etc/app/common/oncall_gateway/legacy_client.py", line 109, in _call_api
    response = method(url, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 575, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 486, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL 'api/v1/slack_team_connectors/check_installation_possible?slack_team_id=T05QKA1FF8W&oncall_org_id=31e3cf55-c921-4790-80c1-7727644d7034&backend=None': No scheme supplied. Perhaps you meant https://api/v1/slack_team_connectors/check_installation_possible?slack_team_id=T05QKA1FF8W&oncall_org_id=31e3cf55-c921-4790-80c1-7727644d7034&backend=None?```

**Comment by dteach** [comment]
+1 
I haven't been able to downgrade to a version that works.

**Comment by dark-brains** [comment]
I manualy set engine image version to 1.3.8 and it is worked, but other newer version has many problems not only slack chatops, also OnCall plugin connection etc..

**Comment by joeyorlando** [comment]
hi there :wave: this _should_ be fixed in #3893. Do you mind upgrading to >= v1.3.105?

**Comment by elburnetto-intapp** [comment]
Hey @joeyorlando, we're also facing this issue too. I've just upgraded the Engines/Celery to v1.3.105, as well as the Grafana plugin, we're still seeing this error happening:

requests.exceptions.MissingSchema: Invalid URL 'api/v1/slack_team_connectors/check_installation_possible?slack_team_id=<redacted>&oncall_org_id=<org_id_redacted>&backend=None': No scheme supplied. Perhaps you meant https://api/v1/slack_team_connectors/check_installation_possible?slack_team_id=<redacted>&oncall_org_id=<redacted>&backend=None?
