### ISSUE TITLE
Grafana OnCall Plugin - "Send Code" Not Working for adding User's Phone Number

### ISSUE THREAD

**Issue by rsrj-bandaru** [grafana/oncall#5449]
### What went wrong?

I deployed the open-source Grafana OnCall plugin with the following setup:

Grafana Version: v11.4.0
OnCall Plugin Version: v1.14.1
Deployment Method: Docker Compose

I successfully integrated OnCall with Twilio, and it was working fine until last week. However, when attempting to add a new user and verify a phone number, clicking "Send Code" does nothing.

Upon checking the logs, I found the following error:

logger=context userId=1 orgId=1 uname=admin t=2025-02-12T17:17:49.650876155Z level=info msg="Request Completed" method=GET path=/api/plugins/grafana-oncall-app/resources/users/ULUJQNXVFKNB9/export_token/ status=404 remote_addr=172.18.0.4 time_ms=134 duration=134.771485ms size=23 referer=https://hostname/a/grafana-oncall-app/users/ULUJQNXVFKNB9 handler=/api/plugins/:pluginId/resources/* status_source=server

### How do we reproduce it?

Steps to Reproduce:
             Deploy Grafana v11.4.0 with OnCall v1.14.1 using Docker Compose.
             Integrate OnCall with Twilio for SMS notifications.
             Navigate to OnCall → Users → Edit -> Phone Verification
             Attempt to add a phone number.
             Click "Send Code" – nothing happens.

Expected Behavior:
         The verification code should be sent via Twilio to the provided phone number.
         No 404 errors should appear in the logs.

Actual Behavior:
        Nothing happens when clicking "Send Code" in the UI.
        A 404 Not Found error appears in the logs when requesting export_token.

Impact:
            I'm blocked from adding new users with phone numbers.
            Existing Twilio integration was working but has suddenly stopped for new users.

### Grafana OnCall Version

v1.14.1

### Product Area

Other

### Grafana OnCall Platform?

None

### Anything else to add?

The issue started suddenly without configuration changes.

**Comment by dhr05074** [comment]
I am experiencing the same issue and have found the following error in the console.

```
Error: Invalid site key or not loaded in api.js: 6LeIPJ8kAAAAAJdUfjO3uUtQtVxsYf93y46mTec1
```

**Comment by rsrj-bandaru** [comment]
Team,

this seems like regression bug (Refer : https://github.com/grafana/oncall/issues/2687)

This is bit critical and we are blocked with this. Can someone Please look into this on Priority basis?

is there any way to disable RECAPTCHA and aloow users to add their phone number.

**Comment by kuzaxak** [comment]
We have the same version with the latest `1.14.2` and `1.13.11`

**Comment by mderynck** [comment]
Issue with reCaptcha should be fixed with 1.14.4

**Comment by ZivRechnitser** [comment]
@mderynck, upgrading the plugin and Grafana oncall helm chart still does not solve the issue.
We still can't add a phone number to users.
In the browser console, we see  `404` on `api/plugins/grafana-oncall-app/resources/users/U2JPXR4XJK739/export_token/`.
The option to add users is blocked.

**Comment by jarmd** [comment]
Hmm
I deployed version 1.14.4 now I'm getting the following error:
Error: Invalid reCAPTCHA client id: null
    at Array.<anonymous> (recaptcha__en.js:259:41)
    at recaptcha__en.js:209:448
    at PhoneVerification.tsx:112:49
    at Generator.next (<anonymous>)
    at f6 (NotificationSettingsTab.tsx:24:64)
    at i (NotificationSettingsTab.tsx:24:64)
    at NotificationSettingsTab.tsx:24:64
    at new fr (zone.js:2702:25)
    at NotificationSettingsTab.tsx:24:64
    at V.<computed> (zone.js:1809:37)

So seems like the phone registration is still not working, but now with a new error !!

**Comment by CTBT** [comment]
We also upgraded to 1.14.4 and still have an issue with it.  We get the same error as @jarmd mentioned and i tried it in 3 different browsers. i´m still getting the same error

**Comment by jarmd** [comment]
Did you try to clear out all your browser data or run in Incognito mode in the browser ctrl+shit+n :)
This was the way I found that it was a browser issue.

/Jan

**Comment by aanzorena** [comment]
We have the same issue.  The problem displayed is the following:


```
￼recaptcha__es_419.js:260 Uncaught (in promise) 
Error: Invalid site key or not loaded in api.js: none
    at Array.<anonymous> (￼recaptcha__es_419.js:260:486)
    at ￼recaptcha__es_419.js:212:13
    at eval (￼PhoneVerification.tsx:458:16)
    at Generator.next (<anonymous>)
    at f6 (￼PhoneVerification.tsx:458:16)
    at i (￼PhoneVerification.tsx:458:16)
    at eval (￼PhoneVerification.tsx:458:16)
    at new Promise (<anonymous>)
    at eval (￼PhoneVerification.tsx:458:16)
```



We have already tried running on Incognito Mode and it did not work .

*On Call plugin Version:* 1.14.4

**Comment by jarmd** [comment]
Okay
Did you only upgrade Oncall and not the Grafana Plugin with it ?
I'm running both Oncall 1.14.4 and the Grafana Plugin 1.14.4
You can see the grafana plugin version in the plugin section of grafana and search for Oncall
When you click that it will tell you which version is installed:

![Image](https://github.com/user-attachments/assets/a8529611-52cb-4caa-8958-42c58a85340f)

Sorry for asking such a low level question, but I have not seen the "Invalid site key or not loaded" error since I upgraded to version 1.14.4 :)

/Jan

**Comment by CTBT** [comment]
Yes, that was indeed the problem! We only upgraded the oncall engine at first. After upgrading the plugin everything worked again. I was not aware that those are two separate components.

**Comment by jarmd** [comment]
Great
I'm happy I was able to help :)
Take care
/Jan
